# Generated by Django 5.1.5 on 2025-02-05 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bode',
            new_name='body',
        ),
    ]
