# Generated by Django 5.1.5 on 2025-02-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='bode',
            new_name='body',
        ),
    ]
